//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.01.03 at 06:02:46 PM CET 
//


package InputFileClasses;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.orienteering.datastandard._3 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ResultList_QNAME = new QName("http://www.orienteering.org/datastandard/3.0", "ResultList");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.orienteering.datastandard._3
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResultList }
     * 
     */
    public ResultList createResultList() {
        return new ResultList();
    }

    /**
     * Create an instance of {@link Id }
     * 
     */
    public Id createId() {
        return new Id();
    }

    /**
     * Create an instance of {@link StartTime }
     * 
     */
    public StartTime createStartTime() {
        return new StartTime();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link Class }
     * 
     */
    public Class createClass() {
        return new Class();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link PersonResult }
     * 
     */
    public PersonResult createPersonResult() {
        return new PersonResult();
    }

    /**
     * Create an instance of {@link ClassResult }
     * 
     */
    public ClassResult createClassResult() {
        return new ClassResult();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResultList }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ResultList }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.orienteering.org/datastandard/3.0", name = "ResultList")
    public JAXBElement<ResultList> createResultList(ResultList value) {
        return new JAXBElement<ResultList>(_ResultList_QNAME, ResultList.class, null, value);
    }

}
